### PR TITLE
updated .gitmodules to use git:// protocol - faster and more reliable

### PR DESCRIPTION
**Pull request by leeoniya**
i updated .gitmodules to use git:// and everything works much faster, with no failures.

actually, i'm confused why an http variant exists at all. are there git flavors that don't support git's own protocol? ::scratches head::

running W7x64, TortoiseGit 1.7.6, msysgit 1.7.8

thanks!

### CODE REVIEW

**Comment by isaiahdw** [comment]
You can see the reasons in this commit comments: 1a0a0b52ce24b5c5051e8a4de0094140e4e521ca

**Comment by leeoniya** [comment]
the reason for the pull request is that git:// proved to work much faster and more reliably. msysgit failed for me consistently to submodule-update at random submodules over http. in my experience, i've never seen http clock faster than git. i kinda guessed that "corp firewalls" was part of the reason. is git:// deprecated on github, then?

**Comment by isaiahdw** [comment]
Odd. I've never had an issue with http:// failing. Are you using you are using git 1.6.6+? Maybe there is something wrong with your git install.

**Comment by leeoniya** [comment]
running W7x64, TortoiseGit 1.7.6, msysgit 1.7.8.

**Comment by cs278** [comment]
You can do this in your gitconfig:

``` ini
[url "git://github.com/"]
        insteadOf = http://github.com/
```

**Comment by leeoniya** [comment]
interesting, i shall try that. thx!

**Pull request closed without merging**
