### PR TITLE
Update index.php

### PR DESCRIPTION
**Pull request by WinterSilence**

### CODE REVIEW

**Comment by KostyaTretyak** [comment]
@WinterSilence, ты что шутишь?
Во-первых, в проекте ещё более 30 раз встречается DIRECTORY_SEPARATOR, почему ты поменял только в index.php?
Во-вторых, если тебя не смущает ухудшение читабельности кода, то зачем такие изменения предлагать для всех?
В третьих, ты подумал за совместимость с предыдущими версиями?

**Comment by WinterSilence** [comment]
@kostyatretyak commented in English, so that everyone is clear. 
this is just an example, if passed, will change everywhere.
I think it only improves the readability of the code, which compatibility problems it can cause?

**Comment by zombor** [comment]
I'm not a fan of this.

**Comment by YAAK** [comment]
I'm not a fan too. Simply reduces readability.

**Comment by WinterSilence** [comment]
I do not think it 
DOCROOT.'vendor'.DIRECTORY_SEPARATOR.'project'.DIRECTORY_SEPARATOR.'core'.DIRECTORY_SEPARATOR.'libname'.EXT;
is more readable than
DOCROOT.'vendor'.DS.'project'.DS.'core'.DS.'libname'.EXT;

Some popular frameworks and CMS use these aliases.

**Comment by zombor** [comment]
Some other popular frameworks also use a `e()` method to alias `echo`. The simple fact is that `DS` just doesn't make any sense unless you are "in the know".

**Comment by WinterSilence** [comment]
@zombor PHP_EOL its too doesn't make any sense, but used. Alternatively, you can use DIRSEPARATOR or DIR_SEPARATOR

**Comment by KostyaTretyak** [comment]
@WinterSilence I spent 10 seconds to search for EOL https://en.wikipedia.org/wiki/EOL... This is called multiple meanings. Now used more unambiguous constants DIRECTORY_SEPARATOR, PHP_EOL... Really could probably replace DIRECTORY_SEPARATOR on DIR_SEPARATOR, but in the context of compatibility, your idea "little to reduce the" cost too much. Strange that you need it to explain.

**Comment by rjd22** [comment]
@WinterSilence @zombor 
I have to see I agree with zombor. You have to know what DS means first before you can use it. Making it less readable.

Use concatenation for long strings or just do one of these:

```
$ds = DIRECTORY_SEPARATOR;
DOCROOT.'vendor'.$ds.'project'.$ds.'core'.$ds.'libname'.EXT;
```

---

```
DOCROOT.'vendor'
.DIRECTORY_SEPARATOR.'project'
.DIRECTORY_SEPARATOR.'core'
.DIRECTORY_SEPARATOR.'libname'.EXT;
```

---

```
DOCROOT.'vendor/project/core/libname'.EXT;
```

**Comment by WinterSilence** [comment]
majority disagrees - close this

**Pull request closed without merging**
