### PR TITLE
Added default value for the Cookie::$salt

### PR DESCRIPTION
**Pull request by velkymx**
Set the default value for the Cookie::$salt that is missing from the bootstrap. It was a new requirement that fails the project on initial setup.

### CODE REVIEW

**Comment by shadowhand** [comment]
No: http://kohanaframework.org/3.3/guide/kohana/cookies

**Comment by velkymx** [comment]
Yes, I know about how to set it, but it would be nice not to have to go back and have to re-add the code each time. Seems like adding it to default or throwing a better error would be helpful - especially to new users.

**Comment by zombor** [comment]
There's already an issue about better handling for this. @Zeelot was planning on taking care of it. We definitely do not want a default value, as that is a big security problem.

**Comment by velkymx** [comment]
Fair enough. I'll keep poking around. Thanks Zombor!

**Pull request closed without merging**
