### PR TITLE
Get build running again on 3.3

### PR DESCRIPTION
**Pull request by acoulton**
Resolve remaining 3.3 build fixes:
- [x] preg_replace/e is not supported on PHP 5.5+ (backport kohana/core#465)
- [x] build doesn't run on HHVM
- [x] APC unittest configuration is not valid if apc is present
- [x] HHVM not showing Location header as expected in request client tests
- [x] HHVM timezone formatting doesn't match expectations

**not ready for merge till travis is green**

This is a continuation of #43 which was merged early (because I wasn't clear enough in description).

### CODE REVIEW

**Comment by acoulton** [comment]
The hhvm build now runs for 3.3, but there are some failures. Mostly these are because APC doesn't exist, presumably we should just skip those tests in HHVM. The other big group seems to be missing Location headers in the various redirect/request client tests which will need investigation. And there's one failing with a date formatting issue.

Do we definitely want to support HHVM with the 3.3 branch? If so I can see about getting these fixed there and then we can merge up into 3.4. I don't expect too many conflicts at the moment.

**Comment by acoulton** [comment]
Actually I'm wrong on the reason for apc failing - it looks like it's an issue with offsetExists returning false when loading the config group. So it may be similar to the issue with the headers, which is also an array keys problem.

Anyone come across problems with arrayobject and keys on hhvm before? I'll need to get an instance and see if I can trace.

**Comment by lenton** [comment]
Great work! :+1:

**Comment by acoulton** [comment]
@lenton thanks :) There are a few temporary-ish workarounds for HHVM issues that I'd hope will be resolved at their end in future - in particular that isset does not behave as expected on ArrayObjects.

Also, discovered that most of the cache module tests weren't running on CI at all (because the various extensions/backends aren't configured). I've reinstated file driver tests, and APC on HHVM - will have a look at the other drivers/environments as part of getting the modules running with their own tests.

**Pull request merged**
