### PR TITLE
Unspecialise application module

### PR DESCRIPTION
**Pull request by lenton**
This PR unspecialises the application module by doing four things:
- Moves cache directory to root
- Moves logs directory to root
- Moves bootstrap.php to root
- Moves application module into modules directory

Making the application module just like any other has many benefits:
- The application module is completely optional, you could delete it and Kohana would still run just fine.
- It removes the need for APPPATH which means it can potentially be deprecated in the future.
- The bootstrap, cache and logs become uncoupled from Kohana modules/CFS so they can be more easily used with other libraries.
- It encourages users to split up their application into multiple modules instead of piling it all in application because they think it's special.

If everyone is in support of this change then I'll PR the changes needed to the other modules in order to make the build pass.

### CODE REVIEW

**Comment by lenton** [comment]
Haha, the build passed because it exited with an error instead of throwing one.

Note to collaborators: Don't merge yet.

**Comment by enov** [comment]
@lenton , I don't want to discourage you, but shouldn't we talk about these changes in issues, before you work on PRs? In general I like the way you think. But unfortunately, issues about directory structures, coding styles, version numbers, etc... tends to generate more discussions and disagreements than bug fixes and features.

**Comment by zombor** [comment]
I think moving things to `DOCROOT` is a bad idea. `DOCROOT` is generally world readable.

**Comment by lenton** [comment]
> but shouldn't we talk about these changes in issues

@enov In hindsight I should have put this up in a issue first to ensure I don't waste my time.

> I think moving things to DOCROOT is a bad idea. DOCROOT is generally world readable.

@zombor We plan on enforcing some kind of public, web-accessable folder so files being in DOCROOT won't be a problem. How are they any more secure being in `/application`?

**Comment by zombor** [comment]
> We plan on enforcing some kind of public, web-accessable folder 

This is what `DOCROOT` is (or should be).

> How are they any more secure being in /application?

`application` is generally not in the web root, or if it is, it's protected away with rewrite rules.

**Comment by lenton** [comment]
> application is generally not in the web root, or if it is, it's protected away with rewrite rules.

The same security precautions can be applied to the bootstrap, cache, and logs too.

**Comment by acoulton** [comment]
@lenton sorry, I'm also a :thumbsdown: on this at the moment.

The biggie - I don't agree with the idea of moving application into modules at all because it would be better IMHO to encourage people by default to separate their app components into multiple composer packages rather than having all the same coupling but just happening to put the files all over a bunch of directories inside /modules. I think we should get rid of /modules altogether by default.

We should also IMHO get away from the idea that everything has to be registered in the CFS, for internal components that don't use transparent extension and don't have views/configs/messages etc there's unnecessary friction and overhead in including their paths in the Kohana::modules call.

I also don't agree with moving bootstrap.php to project root. Depending on the tools in use, the root directory on projects gets cluttered already with composer files, vagrant files, berksfiles, gruntfiles, package.json, travis, scrutinizer, readme, contributing, and a whole pile of stuff. Keeping bootstrap in application makes it easier to find and respects its special (eg runtime) status.

Plus, in my projects I already extract bits of bootstrap (eg routes) into files that sit alongside, and I think we should consider more of that given how long and involved it's getting.

I do agree with the idea of moving cache and logs elsewhere, but if we do:
- I think we should probably agree on pushing DOCROOT down a level first
- Even if we don't then referring to their location as DOCROOT feels wrong, and I think we should introduce a new BASEDIR or something - even if it's the same path for now - to be clear that really they should be outside the web root.
- Really, ideally, we should consider putting logs at least in some completely separate path eg /var/log though this does assume more setup/installation/permissions on servers than we have at the moment. Cache could move to /var/cache or something, but that's a bit trickier because you do generally want it to flush on a deploy and for capistrano etc keeping it somewhere inside the checkout directory means that happens by default.

Whatever happens, we definitely shouldn't merge this without really solid upgrade note documentation and without changing things like example.htaccess to block access to these locations.

**Comment by lenton** [comment]
> The biggie - I don't agree with the idea of moving application into modules at all because it would be better IMHO to encourage people by default to separate their app components into multiple composer packages rather than having all the same coupling but just happening to put the files all over a bunch of directories inside /modules.

Application is a module, it should go in the modules directory alongside the other user-made modules. The good thing about this is that all the ugly Kohana modules would be isolated in one directory.

> I think we should get rid of /modules altogether by default.

The modules directory needs to exist and we need to allow users to create multiple modules for as long as we still use the CFS.

> We should also IMHO get away from the idea that everything has to be registered in the CFS, for internal components that don't use transparent extension and don't have views/configs/messages etc there's unnecessary friction and overhead in including their paths in the Kohana::modules call.

I too agree that we need to move towards completely removing Kohana modules/CFS and this PR does that. Because the bootstrap, cache, and logs are separated from the CFS and all modules are isolated inside the modules directory, it would make this transition easier. The next major version of Kohana packages could possibly end support for the CFS.

> I think we should probably agree on pushing DOCROOT down a level first
> Even if we don't then referring to their location as DOCROOT feels wrong, and I think we should introduce a new BASEDIR or something - even if it's the same path for now - to be clear that really they should be outside the web root.

I'm in support for a project path variable so that DOCROOT remains the public web directory.

**Comment by acoulton** [comment]
> Application is a module, it should go in the modules directory alongside the other user-made modules. The good thing about this is that all the ugly Kohana modules would be isolated in one directory.
> 
> The modules directory needs to exist and we need to allow users to create multiple modules for as long as we still use the CFS.

But there are no "ugly Kohana modules" in the modules directory any more. Your composer configuration puts them in `vendor/kohana/whatever` where they should be - MODPATH is no longer at all relevant for a stock kohana/kohana install.

Your `Kohana::modules` changes already take away any special status of APPPATH and SYSPATH - so there's absolutely nothing stopping a user putting their own application into multiple "modules" in /modules or anywhere else they feel like. 

It's much better IMO for them to break their application into multiple composer packages, separately testable, etc - since that's the only real way to know that your "modules" are actually isolated packages. We should encourage that by dropping the  /modules directory and the MODPATH constant altogether since they're just empty in kohana/kohana.

> The next major version of Kohana packages could possibly end support for the CFS.

The CFS for config files, view (templates), messages etc still has a valid place IMHO. Packages that provide any of those should be registered with `Kohana::modules`, and there should still be an init mechanism for packages that want/need to provide one.

I'd support a future major version of Kohana dropping class loading from (and transparent extension using) the CFS and using the composer autoloader instead - with proper DI so that end-users can instead provide custom implementations in extension classes with new names.

**Pull request closed without merging**
