### PR TITLE
Remove redundant mb_substitute_character line from bootstrap

### PR DESCRIPTION
**Pull request by enov**
This is related to kohana/core#537.

### CODE REVIEW

**Comment by rjd22** [comment]
Was there always something wrong with the build? :/

**Comment by rjd22** [comment]
@enov @lenton I'm not sure but https://travis-ci.org/kohana/kohana/builds tells me something has gone wrong a fel builds ago. Could you guys check if that is your pull request / merge causing it?

**Comment by enov** [comment]
no idea @rjd22 :/

Maybe @acoulton can help us here?

**Comment by enov** [comment]
Hmm.. It says

> Call to undefined method Kohana::init_modules()

Maybe submodules should be updated to track the tip of the branches?

**Comment by acoulton** [comment]
@enov that was still failing because unittest hadn't been updated to call init_modules. Because the official modules are commented out in kohana/kohana's application/bootstrap.php, they are enabled later by the unittest module. Because it wasn't then running the userguide init.php the markdown autoloader was never registered hence the fatal.

Also, your submodule update took everything up to 3.4/develop, but the cache module had unittest fixes in 3.3/develop that hadn't been merged up. I've not checked any other submodules. If we're going to maintain a 3.3/develop and 3.4/develop branch for all the modules, I think we need a better process for making sure that any 3.3 bugfixes get merged up. When I was first getting the build fixed the other week there was quite a lot that had diverged between 3.3 and 3.4.

**Comment by rjd22** [comment]
Maybe we should start doing something like this:
https://github.com/kohana/kohana/issues/50

**Comment by enov** [comment]
Thanks @acoulton :)

**Comment by enov** [comment]
@rjd22 could we now push the big green button :) ⬇

**Pull request merged**
