### PR TITLE
Enable modules before using I18n::lang()

### PR DESCRIPTION
**Pull request by lenton**
The core module needs to be enabled before using the I18n class. The reason it worked before was because the core module was enabled by default before Kohana::modules() was even called.

### CODE REVIEW

**Comment by shadowhand** [comment]
See, this is why we need to have tests fixed. Should I just go revert everything until we can be sure that the fallout from the modules change is complete?

**Comment by lenton** [comment]
I'm very certain that there are no more errors, I've rewritten these commits like three times. I knew I needed to move enabling the modules but forgot to on my last commit.

All unit tests are passing and the hello world example works.

**Comment by kemo** [comment]
Looks good :+1:

**Comment by enov** [comment]
Hey :) I don't think this is good.

The reason `I18n::lang` is defined before defining the modules is to make the PHP runtime aware of the `__()` function defined in `Kohana_I18n`.

Otherwise, Kohana will not be able to throw `module not found` exceptions. Almost all exceptions in Kohana makes use of the `__()` function.

Cheers!

**Comment by lenton** [comment]
We shouldn't rely on Kohana_Exception until all modules are successfully enabled.

**Comment by enov** [comment]
@lenton not only when modules are not found, but also when cache dir is not writable. See here:

https://github.com/kohana/core/blob/3.3/master/classes/Kohana/Core.php#L278

Unfortunately, there is no autoloading mechanism for functions (that RFC by Anthony Ferrara is set for PHP 5.6 but withdrawn: https://wiki.php.net/rfc/function_autoloading). That's why we have the `__` function defined after `Kohana_I18n` . That's very ugly :) we know.

> We shouldn't rely on Kohana_Exception until all modules are successfully enabled.

Or maybe we should not rely on function `__` in `Kohana_Exception`? I suggest, in the constructor:
- we test first `class_exists('I18h')`. it autoloads `I18n` and `Kohana_I18n` classes
- and then test for `function_exists('__')`
- If function `__` does not exist, keep the message as it is without internationalization.

Cheers :)

**Comment by lenton** [comment]
@enov This PR makes it so Kohana::modules() is called before Kohana::init() too, so them exceptions are fine.

**Comment by enov** [comment]
Hmmm, I see now, that's cool.

But I think not being able to load a module is semantically a Kohana exception and should be treated that way, and testing for the availability of the `__` function in `Kohana_Exception` should be done anyways and will make it future proof.

**Comment by gianebao** [comment]
I also suggest either removing the `__()` in `system/views/kohana/error.php` or make a fallback incase it does not exist.

**Comment by lenton** [comment]
@enov If the core fails to be loaded, Kohana_Exception won't be available either.

**Comment by enov** [comment]
> If the core fails to be loaded, Kohana_Exception won't be available either.

That wouldn't be a Kohana exception. At that point of execution, we're still outside of Kohana.

@gianebao , I guess that's a :+1: . Please file an issue describing more, thanks.

**Comment by lenton** [comment]
@enov Huh, you just said you wanted to use Kohana_Exception when loading modules "But I think not being able to load a module is semantically a Kohana exception and should be treated that way"

**Comment by enov** [comment]
@lenton there is no need for exclamations. I know what I just said. At this point `kohana/core` is not just a module, it is Kohana. Come with a proposal to fix the regression you created, otherwise I am obliged to revert this merge.

Cheers!

**Comment by lenton** [comment]
@enov What regression, there is no issue here, we should use a plain old Exception instead of Kohana_Exception for the "module doesn't exist" error.

And why do you think kohana/core is not just a module?

**Comment by enov** [comment]
> What regression, there is no issue here

I explained already the issue, see above.

> we should use a plain old Exception instead of Kohana_Exception for the "module doesn't exist" error.

We can't. I explained that above.

> And why do you think kohana/core is not just a module?

I said _at this point_ it's not just a module, see above. You are welcome to make it just a module, we'll discuss that in that issue/proposal you created.

**Comment by lenton** [comment]
@enov Why can't we use Exception instead of Kohana_Exception when loading modules? I couldn't find your explanation.

**Pull request merged**
